### ISSUE TITLE
Install Ojektiv with Homebrew

### ISSUE THREAD

**Issue by xuv** [Vorror/Objektiv#4]
Love this app. And I see you've put some extra work to maintain it. Thanks a lot for that.
I'd love to be able to install it with Homebrew. Do you think it's possible?

**Comment by cmeury** [comment]
I'm trying to get this fork into homebrew-cask: https://github.com/Homebrew/homebrew-cask/pull/82308

However, since the original repo has been abandoned and the developers's websites are out of order -- it might be okay to take over the source code and re-release under a new, similar name, as already suggested in another issue #2

**Comment by cmeury** [comment]
Was declined because it's a fork. Would probably need to prefix it as `vorror-objektiv`, but then it does not have enough stars to warrant inclusion in homebrew-casks. So this seems to be a non-starter.

**Comment by cmeury** [comment]
I suggest to close this in favor of https://github.com/nthloop/Objektiv/issues/16
